const Pgrup qsm[] = {
	{"***:"," QUITTIERBARE   ","       ", P&Stoermeld,							 ASCII_FORM, 0, P&vis,	V1, 0, 0},
	{"*01:"," QSM VORHANDEN ?","       ", P&un_qsm,			 						JANEIN_FORM, 0, P&vis,	V1, 0, 0},

//**PARSER-BEGIN-qsm[]**  AUTOMATISCHE ERZEUGUNG *****
// Diese Zeilen wurde automatisch am : 07.06.2018 um 09:37:42 generiert und entspricht der Systemversion nach 19.07.2017 10:21:03!!!
// Path: C:\RIEcon36C\Softwarepool\Softwarepool_PES_2018\KE_SNW81\KE_R_1s03_JMX81\User\Komtabparser.exe
	{"ANL:"," AUSSENLUFTTEMP.","       ", P&alarmtab[0].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ANL:"," SMGRUP STANDARD","       ", P&alarmtab[1].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ANL:"," SMGRUP FUEHLER ","       ", P&alarmtab[2].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ANL:"," SMGRUP MODULE  ","       ", P&alarmtab[3].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ANL:"," SSTM PUMPENBUS?","       ", P&alarmtab[4].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"ANL:"," SSM EXT.1 HKV ?","       ", P&alarmtab[5].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"ANL:"," SSM EXT.2 WPU ?","       ", P&alarmtab[6].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"ANL:"," SSM EXT.3 KES ?","       ", P&alarmtab[7].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"ANL:"," EXTERNE SSM ?  ","       ", P&alarmtab[8].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"KES:"," VL-KESSEL  TVK1","       ", P&alarmtab[9].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"KES:"," ANFORDER.EXT 1 ","       ", P&alarmtab[10].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"KES:"," ANFORDER.EXT 2 ","       ", P&alarmtab[11].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"KES:"," SSM KESSEL ?   ","       ", P&alarmtab[12].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"KES:"," HANDBETRIEB ?  ","       ", P&alarmtab[13].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"NK1:"," VORL.     TVNK1","       ", P&alarmtab[14].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"NK1:"," RUECKL.   TRNK1","       ", P&alarmtab[15].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"NK1:"," ANFORDER.EXT 1 ","       ", P&alarmtab[16].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"NK1:"," ANFORDER.EXT 2 ","       ", P&alarmtab[17].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"NK1:"," SM REGELABW.?  ","       ", P&alarmtab[18].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"NK1:"," SM STW NK1 ?   ","       ", P&alarmtab[19].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"NK1:"," SM PU NK1     ?","       ", P&alarmtab[20].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"NK1:"," HANDBETRIEB ?  ","       ", P&alarmtab[21].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKL:"," VL-HEIZUNG  TVH","       ", P&alarmtab[22].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKL:"," RL-HEIZUNG  TRH","       ", P&alarmtab[23].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKL:"," SPEI. OB.TSPo-L","       ", P&alarmtab[24].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKL:"," SPEI. MI.TSPm-L","       ", P&alarmtab[25].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKL:"," SPEI. UN.TSPu-L","       ", P&alarmtab[26].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKL:"," ANFORDER.EXT 1 ","       ", P&alarmtab[27].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKL:"," ANFORDER.EXT 2 ","       ", P&alarmtab[28].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKL:"," SM REGELABW.?  ","       ", P&alarmtab[29].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"HKL:"," SM PU LK      ?","       ", P&alarmtab[30].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"HKL:"," HANDBETRIEB ?  ","       ", P&alarmtab[31].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKS:"," SPEICHER MAX ? ","       ", P&alarmtab[32].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"HKS:"," HANDBETRIEB ?  ","       ", P&alarmtab[33].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," KOLLEKTOR   TS1","       ", P&alarmtab[34].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," SOLAR-HEIZ. TS3","       ", P&alarmtab[35].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," SOLAR-PUFF. TS4","       ", P&alarmtab[36].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," RL-SOLAR    TS6","       ", P&alarmtab[37].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," PUFFER o TSPo-P","       ", P&alarmtab[38].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," PUFFER u TSPu-P","       ", P&alarmtab[39].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SOL:"," SM DRU.KOL.MAX?","       ", P&alarmtab[40].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM DRU.KOL.MIN?","       ", P&alarmtab[41].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM DRU.PUF.MAX?","       ", P&alarmtab[42].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM DRU.PUF.MIN?","       ", P&alarmtab[43].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," VOL.STR. ALARM?","       ", P&alarmtab[44].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM PU SOL     ?","       ", P&alarmtab[45].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," SM PU PK      ?","       ", P&alarmtab[46].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SOL:"," HANDBETRIEB  ? ","       ", P&alarmtab[47].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ZLT;"," OBJ-ORT FEHLT ?","       ", P&alarmtab[48].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"ZLT;"," PIN FEHLT ?    ","       ", P&alarmtab[49].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SYS;"," DAT-ERROR R37_1","       ", P&alarmtab[50].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SYS;"," DAT-ERROR R37_2","       ", P&alarmtab[51].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SYS;"," DAT-ERROR R38_1","       ", P&alarmtab[52].alspeicher,		JANEIN_FORM, 0, P&vis,	V1, 0, 0},
	{"SYS;"," RTC-UHR ERROR  ","       ", P&alarmtab[53].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SYS;"," MAIN-CRASH:TASK","       ", P&alarmtab[54].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SYS;"," FerroRAM2 FEHLT","       ", P&alarmtab[55].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
	{"SYS;"," SDHC-Card FEHLT","       ", P&alarmtab[56].alspeicher,		JANEIN_FORM, 0, P&hid3,	V0, 0, 0},
//**PARSER-ENDE-qsm[]**  AUTOMATISCHE ERZEUGUNG *****

	{" 99:"," QUITTIER-TASTE "," EIN=1 ", P&quit_taste,			 						US_CHAR, 0, P&hid1,	V1, 0, 0},

};

